name: Linting and Testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Yarn packages
        run: yarn install

      - name: Build Project
        run: npm run build
      
      - name: Run ESLint Report
        run: yarn lint:report
        # continue on error, so it still reports it in the next step
        continue-on-error: true

      - uses: actions/upload-artifact@v2
        with:
          name: eslint_report.zip
          path: eslint_report.json
