name: Linting

on:
  push:
    branches:
      - master
      - dev
  pull_request_target:
    types: [opened, reopened, synchronize]

# needs write to add annotations
permissions:
  checks: write
  contents: write

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_args: --max-warnings=0 src
          eslint_extensions: tsx,ts
          eslint_auto_fix: false